[package]
name = "tiny_env"
version = "0.1.0"
edition = "2021"
about = "get environment variable from config"
license = "WTFPL"

[dependencies]
clap = { version = "4.0.28", features = ["derive"] }
env_logger = "0.10.0"
log = "0.4.17"
toml = "0.5.9"
